django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    # path('registre/', include('e_registre.urls')),
    path('', include('e_registre.urls', namespace='e_registre')),
]

e_registre/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'e_registre'

urlpatterns = [
	path('', views.home, name='home'),
	path('ajouter/<categorie>/', views.add_personne, name='ajouter'),
	path('<categorie>/<int:id>/', views.detail, name='detail'),
	path('liste/<categorie>/', views.liste, name='liste'),
	path('now', views.date_is, name="heure"),

	# ********** AJAX REQUEST URLs*******************
	path('visites/nouveau/<categorie>/<int:id>/', views.debut_visite),
	path('visites/fin/<categorie>/<int:id>/', views.fin_visite),
	
]

e_registre/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

# Create your models here.


class Matiere(models.Model):
	libelle = models.CharField(max_length=50, default="M")

	def __str__(self):
		return self.libelle

class Personne(models.Model):
	nom = models.CharField(max_length=50)
	prenom = models.CharField(max_length=50)
	sexe = models.CharField(max_length=1)
	telephone = models.CharField(max_length=100)
	
	def __str__(self):
		return f"{self.nom}"

class Visiteur(Personne):

	def __str__(self):
		return f"{self.nom}"

class Etudiant(Personne):
	filiere = models.ForeignKey('Filiere', on_delete=models.CASCADE, null=True)
	def __str__(self):
		return f"{self.nom}"

class Personnel(Personne):
	departement = models.ForeignKey('Departement', on_delete=models.CASCADE, null=True)
	def __str__(self):
		return f"{self.nom}"

class Enseignant(Personne):
	matieres = models.ManyToManyField(Matiere, through='Enseignement', related_name='+')
	def __str__(self):
		return f"{self.nom}"

class Visite(models.Model):
	visiteur = models.ForeignKey('Personne', on_delete=models.CASCADE)
	date_de_visite = models.DateField(default=timezone.now)
	heure_darrive = models.TimeField(default=timezone.now)
	heure_depart = models.TimeField(null=True, blank=True)
	motif = models.TextField(null=True, blank=True)

	def __str__(self):
		return self.visiteur.nom

class Filiere(models.Model):
	libelle = models.CharField(max_length=50)

	def __str__(self):
		return self.libelle

class Departement(models.Model):
	libelle = models.CharField(max_length=50)

	def __str__(self):
		return self.libelle

class Enseignement(models.Model):
	matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
	enseignant = models.ForeignKey(Enseignant, on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.enseignant.libelle} enseigne {self.matiere.libelle}"

e_registre/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import *
from .utils import get_current_user
 
 
class EtudiantForm(forms.ModelForm):
 
	class Meta:
		model = Etudiant
		fields = "__all__"
		widgets = {
			'nom': forms.TextInput(attrs={'class': 'selectpicker form-control',
											'placeholder': 'Entrez nom'}),
			'prenom': forms.TextInput(attrs={'class': 'selectpicker form-control',
														'placeholder': 'Entrez prenom'}),
			'sexe': forms.TextInput(attrs={'class': 'selectpicker form-control',
														'placeholder': 'Entrez votre sexe'}),
			'telephone': forms.TextInput(attrs={'class': 'selectpicker form-control',
											'placeholder': 'Entrez telephone'}),
			}

class EnseignantForm(forms.ModelForm):
 
	class Meta:
		model = Enseignant
		fields = "__all__"
		widgets = {
			'nom': forms.TextInput(attrs={'class': 'selectpicker form-control',
											'placeholder': 'Entrez nom'}),
			'prenom': forms.TextInput(attrs={'class': 'selectpicker form-control',
														'placeholder': 'Entrez prenom'}),
			'sexe': forms.TextInput(attrs={'class': 'selectpicker form-control',
														'placeholder': 'Entrez votre sexe'}),
			'telephone': forms.TextInput(attrs={'class': 'selectpicker form-control',
											'placeholder': 'Entrez telephone'}),
			}

class PersonnelForm(forms.ModelForm):
 
	class Meta:
		model = Personnel
		fields = "__all__"
		widgets = {
			'nom': forms.TextInput(attrs={'class': 'selectpicker form-control',
											'placeholder': 'Entrez nom'}),
			'prenom': forms.TextInput(attrs={'class': 'selectpicker form-control',
														'placeholder': 'Entrez prenom'}),
			'sexe': forms.TextInput(attrs={'class': 'selectpicker form-control',
														'placeholder': 'Entrez votre sexe'}),
			'telephone': forms.TextInput(attrs={'class': 'selectpicker form-control',
											'placeholder': 'Entrez telephone'}),
			}


class VisiteurForm(forms.ModelForm):

	class Meta:
		model = Visiteur
		fields = "__all__"
		widgets = {
			'nom': forms.TextInput(attrs={'class': 'selectpicker form-control',
											'placeholder': 'Entrez nom'}),
			'prenom': forms.TextInput(attrs={'class': 'selectpicker form-control',
														'placeholder': 'Entrez prenom'}),
			'sexe': forms.TextInput(attrs={'class': 'selectpicker form-control',
														'placeholder': 'Entrez votre sexe'}),
			'telephone': forms.TextInput(attrs={'class': 'selectpicker form-control',
											'placeholder': 'Entrez telephone'}),
		}


class VisiteForm(forms.ModelForm):
	class Meta:
		model = Visite
		fields = ("visiteur", 'motif',"heure_depart")
		widgets = {
			'visiteur': forms.Select(attrs={'class': 'selectpicker form-control',}),
			'motif': forms.Textarea(attrs={'class': 'selectpicker form-control',
											'placeholder': 'Motif de la visite'}),
		}

e_registre/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib import messages
from django.http import HttpResponse, Http404

from .forms import EtudiantForm, VisiteForm, VisiteurForm, EnseignantForm, PersonnelForm
from .models import Etudiant, Visiteur, Enseignant, Personnel, Visite
import datetime

categories = {"etudiant"  : Etudiant, 
			  "autre"     : Visiteur, 
			  "enseignant": Enseignant, 
			  "personnel" : Personnel}

motifs = {"etudiant"  : "Cours", 
		  "autre"     : "Visiteur", 
		  "enseignant": "Enseignant", 
		  "personnel" : "Personnel"}

def add_personne(request, categorie):
	print(categorie)
	categories = {"etudiant" : EtudiantForm, "autre": VisiteurForm, "enseignant": EnseignantForm, "personnel": PersonnelForm}
	if request.method ==  'POST':
		f = categories[categorie](request.POST)
		if f.is_valid():
			personne = f.save()
			return redirect(reverse('e_registre:liste', args=[categorie]))

	else:
		f = categories[categorie]()
	return render(request, 'e_registre/ajout_personne.html', {'form': f})

def liste(request, categorie):
	personnes = categories[categorie].objects.all()
	return render(request, 'e_registre/liste.html', {'personnes': personnes, 'cate': categorie})

def detail(request, categorie, id):
	personne = get_object_or_404(categories.get(categorie), id=id)
	visites = Visite.objects.filter(visiteur=personne)
	# personne.save()
	return render(request, 'e_registre/detail.html', {'visites': visites, "visiteur": personne})

def home(request):
	if request.method == "GET":
		categorie = request.GET.get("categorie")
		nom = request.GET.get("name")
		if categorie == None:
			categorie = "etudiant"
		if nom == None:
			
			personnes = categories[categorie].objects.all()
			print(personnes)
		else:
			personnes = categories[categorie].objects.filter(nom__contains=nom)
		visites = {}
		for p in personnes:
			visites_de_p = Visite.objects.filter(visiteur=p).order_by("-date_de_visite")
			if len(visites_de_p) == 0:
				visites[p] = ("", "")
			else:
				visites[p] = (visites_de_p[0].heure_darrive, visites_de_p[0].heure_depart)
		print(visites)
	if visites == {} : visites = { p : ("", "") for p in personnes }
	contexte = {"personnes" : visites, 'cate': categorie}
	if request.is_ajax():
		return render(request, 'layout/ajax_home.html', contexte)
	return render(request, 'e_registre/home.html', contexte)

def date_is(request):
	now = datetime.datetime.now()
	now = now.strftime("%Y %M %d %H-%M-%S")
	return render(request, 'e_registre/now.html', locals())

def debut_visite(request, categorie, id):
	if request.is_ajax():
		visiteur = get_object_or_404(categories.get(categorie), id=id)
		visite = Visite(visiteur=visiteur, motif=motifs[categorie])
		visite.save()
		now = visite.heure_darrive.now()
		print(now.strftime("%HH %Mm %Ss"))
		return HttpResponse(f"{now.strftime('%H:%M:%S')}")

def fin_visite(request, categorie, id):
	if request.is_ajax():
		visiteur = get_object_or_404(categories.get(categorie), id=id)
		visite = Visite.objects.filter(visiteur=visiteur).order_by("-date_de_visite")[0]
		visite.heure_depart = datetime.datetime.now()
		visite.save()
		print(visite)
		return HttpResponse(f"{visite.heure_depart.now().strftime('%H:%M:%S')}")

e_registre/templates/e_registre/ajout_personne.html
{% extends 'base.html' %}
 
{% load static %}
 
{% block main %}
 
	<form action="" class="form-horizontal" method="post">
 
		{% csrf_token %}
 
		<!-- {{ form.original_code.errors }}
 
		{{ form.original_code }} -->
 
		<hr>
 
		<!-- {{ form.nom.errors }} -->
 
		<div class="form-group">
			<label for="{{ form.nom.id_for_label }}" class="col-sm-2  control-label">Nom</label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				{{ form.nom }}
			</div>
		</div>
 
		<div class="form-group">
			<label for="{{ form.prenom.id_for_label }}" class="col-sm-2  control-label">Prenom</label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				{{ form.prenom }}
			</div>
		</div>

		<div class="form-group">
			<label for="{{ form.sexe.id_for_label }}" class="col-sm-2  control-label">Sexe</label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				{{ form.sexe }}
			</div>
		</div>
 
		<div class="form-group">
			<label for="{{ form.telephone.id_for_label }}" class="col-sm-2  control-label">Telephone</label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				{{ form.telephone }}
			</div>
		</div>
 
		<div class="form-group">
			<label for="inputEmail3" class="col-sm-2 control-label"></label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				<button type="submit" class="btn btn-primary">Ajouter</button>
			</div>
		</div>
 
	</form>
 
{% endblock %}

e_registre/templates/e_registre/ajout_visite.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

	<form action="" class="form-horizontal" method="post">

		{% csrf_token %}

		<hr>

		<div class="form-group">
			<label for="{{ form.nom.id_for_label }}" class="col-sm-2  control-label">Nom</label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				{{ form.visiteur }}
			</div>
		</div>

		<div class="form-group">
			<label for="{{ form.prenom.id_for_label }}" class="col-sm-2  control-label">Prenom</label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				{{ form.prenom }}
			</div>
		</div>

		<div class="form-group">
			<label for="{{ form.sexe.id_for_label }}" class="col-sm-2  control-label">Sexe</label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				{{ form.sexe }}
			</div>
		</div>

		<div class="form-group">
			<label for="{{ form.telephone.id_for_label }}" class="col-sm-2  control-label">Telephone</label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				{{ form.telephone }}
			</div>
		</div>

		<div class="form-group">
			<label for="inputEmail3" class="col-sm-2 control-label"></label>
			<div class="col-lg-10 col-md-10 col-sm-10">
				<button type="submit" class="btn btn-primary">Ajouter</button>
			</div>
		</div>

	</form>

{% endblock %}

e_registre/templates/e_registre/detail.html
{% extends 'base.html' %}
 
{% load static %}
 
{% block main %}
 
	<div class="media post-meta">
		<div class="media-body">
			<h4 class="media-heading">{{ etudiant.nom|default:"Untitled" }}</h4>
			<p>
				<i class="fas fa-user" data-toggle="tooltip" title="" data-original-title="Paste creator"></i> by
				{{ etudiant.prenom|capfirst }} &nbsp;
				<i class="fas fa-calendar-alt" data-toggle="tooltip" title="" data-original-title="Creation Date" ></i>
				<!-- <time title="{{ etudiant.created_on }}">{{ etudiant.created_on|date:"M jS,  Y" }}</time> &nbsp;</span> -->
				<i class="fas fa-eye"  data-toggle="tooltip" title="" data-original-title="Visits to this paste" ></i>
				{{ etudiant.sexe }} &nbsp;&nbsp;

			</p>
		</div>
 
	</div>
 
	<h5><i class="fas fa-chart-line"></i> Liste des visites de l'étudiant {{ visiteur.nom|upper }}</h5>
    <hr>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Date de visite</th>
            <th>Heure d'arrivée</th>
            <th>Heure de départ</th>
            <th>Motif</th>
        </tr>
        </thead>
        <tbody>

        {% for visite in visites %}
            <tr>
                <td><i class="fas fa-clock"></i>
                     {{ visite.date_de_visite }}
                </td>
                <td title=""><i class="fas fa-clock"></i> {{ visite.heure_darrive}}</td>
                <td><i class="fas fa-clock"></i> {{ visite.heure_depart|default:"Visite nom terminée" }}</td>
                <td>{{ visite.motif }}</td>
            </tr>
        {% empty %}
            <tr class="text-center">
                <td colspan="4">Aucune visite effectuée.</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <div >
        <button class="btn btn-primary">
            <a>Nouvelle visite</a>
        </button>
    </div>
 
{% endblock %}

e_registre/templates/e_registre/home.html
{% extends 'base.html' %}
{% load static %}
{% load my_filters %}
 
{% block main %}
 
	<div class="form-group">
		<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-3">
				<select name="categorie" id="categorie" class="form-control">
					<option value="etudiant">Etudiants</option>
					<option value="enseignant">Enseignants</option>
					<option value="personnel">Personnels</option>
					<option value="autre">Autres visiteurs</option>
				</select>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6">
				<input id="mysearch" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="name" required>
			</div>
		</div>
	</div>

	<table class="table table-bordered">
		<tr>
			<th>Nom</th>
			<th>Arrivée</th>
			<th>Départ</th>
		</tr>

		<tbody id="ajax-response">
		{% include 'layout/ajax_home.html' %}
		</tbody>

	</table>
 
{% endblock %}

{% block scripts %}
	<script type="text/javascript">
		
		setTimeout(function () {
			$("#home-loader").css("display", "none");
			// $("#home-loader").css("background", "gray");
			$("#main").fadeIn(2000);
		}, 3000);

		$(".btn-arrivee").on("click", function () {
			window.curr_tag = this;
			$.ajax({
				url : "visites/nouveau/{{cate}}/" + window.curr_tag.value + "/",
				type : 'GET',
				dataType : 'text',
				success : function(rep, statut){
					$(window.curr_tag.nextElementSibling).text(rep);
				},
				error : function(resultat, statut, erreur){
					console.log(erreur);
					alert("erreur AJAX");
				},
			});
			$(this).attr("disabled", true);
		});
		$(".btn-depart").on("click", function () {
			var arrivee = this.parentElement.previousElementSibling.firstElementChild;
			window.tag = this;
			$.ajax({
				url : "visites/fin/{{cate}}/" + window.tag.value + "/",
				type : 'GET',
				dataType : 'text',
				success : function(rep, statut){
					$(window.tag.nextElementSibling).text(rep);
				},
				error : function(resultat, statut, erreur){
					console.log(erreur);
					alert("erreur AJAX");
				},
			});
			$(arrivee).attr("disabled", true);
			$(this).attr("disabled", true);
		});
		$("#categorie").on("change", function () {
			console.log(this.value);
			$.get("?categorie="+this.value, function (data) {
				// console.log(data);
				$("#ajax-response").html(data);
			});
		});

		$("#mysearch").on("keyup", function () {
			url = "?categorie="+this.parentElement.parentElement.firstElementChild.firstElementChild.value+"&name="+this.value;
			console.log(url);
			$.get(url, function (data) {
				// console.log(data);
				$("#ajax-response").html(data);
			});
		});

	</script>
{% endblock %}

e_registre/templates/e_registre/liste.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Liste des Etudiants
{% endblock %}

{% block main %}

    <h5><i class="fas fa-chart-line"></i> Liste des {{cate}}s</h5>
    <hr>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Sexe</th>
            <th>Telephone</th>
        </tr>
        </thead>
        <tbody>

        {% for personne in personnes %}
            <tr>
                <td><i class="fas fa-user"></i>
                    <a href="{% url 'e_registre:detail' categorie=cate id=personne.id %}">
                        {{ personne.nom }}
                    </a>
                </td>
                <td title="">{{ personne.prenom}}</td>
                <td>{{ personne.sexe }}</td>
                <td>{{ personne.telephone }}</td>

            </tr>
        {% empty %}
            <tr class="text-center">
                <td colspan="4">Il n'existe aucune personne.</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <div >
        <button class="btn btn-primary"><a href="{% url 'e_registre:ajouter' cate %}">Ajouter nouveau</a></button>
    </div>

{% endblock %}

e_registre/templates/e_registre/new_visite.html
{% extends 'base.html' %}
 
{% load static %}
 
{% block main %}
 
	test
 
{% endblock %}

e_registre/templates/e_registre/now.html
{% extends "base.html" %}
{% load static %}

{% block title %}Now{% endblock %}

{% block content %}
	<h1>Today is : 
		<code>{{ now }}</code>
	</h1>
{% endblock %}

e_registre/templates/layout/ajax_home.html
{% load static %}
{% load my_filters %}
{% for personne in personnes %}
<tr>
	<td>
		<i class="fas fa-user"></i>
		<a href="{% url 'e_registre:detail' categorie=cate id=personne.id %}">
			{{ personne.nom }} {{ personne.prenom}}
		</a>
	</td>

	<th class="tes">
		<button class="btn btn-success btn-arrivee" value="{{ personne.id }}"  {% if personnes|item:personne|item:0 %}disabled{% endif %}>
			Maintenant
		</button>
		<em class="heure-arrivee">{{ personnes|item:personne|item:0 }}</em>

		{% if personnes|item:personne|item:0 and personnes|item:personne|item:1 %}
		<button class="btn btn-primary new-visite">New</button>
		{% endif %}

	</th>
	<th>
		<button class="btn btn-danger btn-depart" value="{{ personne.id }}" {% if personnes|item:personne|item:1 %}disabled{% endif %}>
			Maintenant
		</button>
		<em class="heure-depart">{{ personnes|item:personne|item:1 }}</em>
	</th>
</tr>
{% empty %}
<tr class="text-center">
	<td colspan="4">Oups!!!</td>
</tr>
{% endfor %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}E-Registre{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'e_registre/css/bootstrap.min.css' %}" >
	<link rel="stylesheet" href="{% static 'e_registre/css/bootstrap-select.min.css' %}" >
	<link href="{% static 'e_registre/css/all.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'e_registre/css/main.css' %}">
	<link rel="stylesheet" href="{% static 'e_registre/css/default.css' %}">
</head>
<body>
<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>

<div id="home-loader">
	<img id="gif-img" src="{% static 'e_registre/image/ajax-loader.gif' %}" alt=""/>
	<img id="parchemin" src="{% static 'e_registre/image/parchemin.jpg' %}" alt=""/>
</div>

<div id="main">
	<nav class="navbar navbar-default navbar-inverse navbar-fixed-top entete">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
					<a class="navbar-brand" href="{% url 'e_registre:home' %}">E-Registre</a>
			</div>
	 
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li {% if request.path == '/personnels' %}class='active'{% endif %} >
						<a href="{% url 'e_registre:liste' 'personnel' %}">Personnel</a>
					</li>
					<li {% if request.path == '/ensaignants' %}class='active'{% endif %} >
						<a href="{% url 'e_registre:liste' 'enseignant' %}">Enseignant</a>
					</li>
					<li {% if request.path == '/etudiants/' %}class='active'{% endif %}>
						<a href="{% url 'e_registre:liste' 'etudiant' %}">Etudiants<span class="sr-only">(current)</span></a>
					</li>
					<li {% if request.path == '/visiteurs/' %}class='active'{% endif %}>
						<a href="{% url 'e_registre:liste' 'autre' %}">Visiteurs</a>
					</li>
					<!-- <li {% if request.path == '/contact/' %}class='active'{% endif %}>
						<a href="">Contact</a>
					</li> -->
				</ul>
	 
				<form action="" class="navbar-form navbar-left" method="get">
					<div class="form-group">
						<input type="text" name="query" class="form-control" placeholder="Search" value="" disabled="">
					</div>
				</form>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
						   aria-haspopup="true" aria-expanded="false">
							{% if request.user.is_authenticated %}
								{{ request.user.username|upper }}
							{% else %}
								GUEST
							{% endif %}
							<span class="caret"></span>
						</a>
						{% if request.user.is_authenticated %}
							<ul class="dropdown-menu">
								<li><a href="http://localhost:8000/admin/">admin</a></li>
								<li><a href="">Account Details</a></li>
								<li><a href="">Settings</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="">Logout</a></li>
							</ul>
						{% else %}
							<ul class="dropdown-menu">
								<li><a href="">Sign Up</a></li>
								<li><a href="">Login</a></li>
							</ul>
						{% endif %}
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
	 
	<div class="container">
	 
		<div class="row">
	 
			<div class="col-lg-9 col-md-9">
	 
				{% if not request.user.is_authenticated and not request.path == '/login/'  %}
					<p class="alert alert-info">
						<a href="" class="alert-link">Login</a> to access other cool features.
					</p>
				{% endif %}
	 
	 
				{% block main %}
					{#  override this block in the child template  #}
				{% endblock %}
	 
			</div>
	 
			<div class="col-lg-3 col-md-3 text-center hidden-sm hidden-xs">
				<p>Visites Recentes</p>
	 
				<div class="list-group">
					<a href="#" class="list-group-item">
						<h5 class="list-group-item-heading"><span class="fas fa-globe"
							"></span> Wisdom</h5>
						<p class="list-group-item-text">21 sec ago.</p>
					</a>
	 
					<a href="#" class="list-group-item">
						<h5 class="list-group-item-heading"><span class="fas fa-globe"
							"></span> Christophe</h5>
						<p class="list-group-item-text">21 sec ago.</p>
					</a>
					<a href="#" class="list-group-item">
						<h5 class="list-group-item-heading"><span class="fas fa-globe"
							"></span> DeLaCruz</h5>
						<p class="list-group-item-text">21 sec ago.</p>
					</a>
					<a href="#" class="list-group-item">
						<h5 class="list-group-item-heading"><span class="fas fa-globe"
							"></span> Batako</h5>
						<p class="list-group-item-text">21 sec ago.</p>
					</a>
					<a href="#" class="list-group-item">
						<h5 class="list-group-item-heading"><span class="fas fa-globe"
							"></span> Balakim</h5>
						<p class="list-group-item-text">21 sec ago.</p>
					</a>
					<a href="#" class="list-group-item">
						<h5 class="list-group-item-heading"><span class="fas fa-globe"
							"></span> Nobody</h5>
						<p class="list-group-item-text">21 sec ago.</p>
					</a>
					<a href="#" class="list-group-item">
						<h5 class="list-group-item-heading"><span class="fas fa-globe"
							"></span> Sam</h5>
						<p class="list-group-item-text">21 sec ago.</p>
					</a>
					<a href="#" class="list-group-item">
						<h5 class="list-group-item-heading"><span class="fas fa-globe"
							"></span> MHD</h5>
						<p class="list-group-item-text">21 sec ago.</p>
					</a>
				</div>
	 
			</div>
		</div>
	</div>
	 
	<hr>
	 
	<footer>
		<div class="social-icons">
			<div class="container text-center">
				<ul class="list-inline">
					<li class="list-inline-item social-github">
						<a href="https://github.com/">
							<i class="fab fa-github"></i>
						</a>
					</li>
					<li class="list-inline-item social-twitter">
						<a href="https://twitter.com/">
							<i class="fab fa-twitter-square"></i>
						</a>
					</li>
					<li class="list-inline-item social-facebook">
						<a href="https://www.facebook.com/">
							<i class="fab fa-facebook-square"></i>
						</a>
					</li>
					<li class="list-inline-item social-google-plus">
						<a href="https://plus.google.com/">
							<i class="fab fa-google-plus-g"></i>
						</a>
					</li>
				</ul>
			</div>
		</div>
	 
		<div class="main-footer">
			<div class="container text-center">
				<ul>
					<li><a href="#">Source Code</a></li>
					<li><a href="#">OverIQ</a></li>
					<li><a href="#">Contact</a></li>
					<li><a href="#">Other Tutorials</a></li>
				</ul>
			</div>
		</div>
	</footer>
</div>
 
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'e_registre/js/jquery.js' %}"></script>
 
<!-- Include all compiled plugins (below), or include individual files as needed -->
<!-- Latest compiled and minified JavaScript -->
<script src='{% static "e_registre/js/bootstrap.min.js" %}'></script>
 
<!-- Latest compiled and minified JavaScript -->
<script src='{% static "e_registre/js/bootstrap-select.min.js" %}'></script>
 
<script>
	$(function () {
		$('[data-toggle="tooltip"]').tooltip()
	})
 
</script>

{% block scripts %}{% endblock %}
 
</body>
</html>